name: agu24workshop
channels:
  - conda-forge
  - nodefaults
dependencies:
  - gmt=6.5.0
  - jupyterlab=4.2.5
  - pygmt=0.13.0
  - python=3.12
  # Tutorial 2 - pandas and GeoPandas, Tutorial 4 - Geophysics (Seismology)
  - pandas=2.2.2
  - geopandas=1.0.1
  # Tutorial 3 - Xarray
  - gcsfs=2024.10.0
  - xarray=2024.10.0
  - zarr=2.18.3
  # Tutorial 5 - 3-D Topography
  - rioxarray=0.17.0
  # Optional dev dependencies
  - jupyter-book=1.0.2
  - pre-commit
  - sphinx_gmt
  - sphinxcontrib-youtube