name: agu24workshop
channels:
  - conda-forge
  - nodefaults
dependencies:
  - gmt=6.5.0
  - jupyterlab=4.2.5
  - pygmt=0.13.0
  - python=3.12
  # Xarray tutorial
  - xarray=2024.10.0
  - gcsfs=2024.10.0
  - zarr=2.18.3
  # Optional dependencies
  - geopandas=1.0.1
  - jupyter-book=1.0.2
  # Optional dev dependencies
  - pre-commit
