name: agu24workshop
channels:
  - conda-forge
  - nodefaults
dependencies:
  - gmt=6.5.0
  - jupyterlab=4.2.5
  - pygmt=0.13.0
  - python=3.12
  - jupyter-book=1.0.2
  # Tutorial 2 - pandas and GeoPandas, Tutorial 4 - Geophysics (Seismology)
  - pandas=2.2.2
  - geopandas=1.0.1
