name: agu24workshop
channels:
  - conda-forge
  - nodefaults
dependencies:
  - gmt=6.5.0
  - jupyterlab=4.2.5
  - pygmt=0.13.0
  - python=3.12
  # Optional dependencies
  - geopandas=1.0.1
  - jupyter-book=1.0.2
  - rioxarray=0.17.0
